from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum


class SegmentStatus(Enum):
    PENDING = "PENDING"       # Gap detected, no text yet
    GENERATED = "GENERATED"   # Text generated by Gemini
    FITTED = "FITTED"         # Text fits the gap, TTS fits
    OVERFLOW = "OVERFLOW"     # TTS audio longer than gap — needs manual fix
    SKIPPED = "SKIPPED"       # Gap too short or user removed description


@dataclass
class ADSegment:
    id: int                          # Sequential segment number
    gap_start_ms: int                # Gap start in original audio (ms)
    gap_end_ms: int                  # Gap end (ms)
    gap_duration_ms: int             # Gap duration (ms)
    max_words: int                   # Max words at AD_WORDS_PER_MINUTE
    text: str = ""                   # Audio description text (PL)
    text_word_count: int = 0         # Actual word count in text
    tts_audio: bytes | None = None   # Synthesised audio (PCM 24kHz 16-bit)
    tts_duration_ms: int | None = None  # Actual TTS audio duration
    status: SegmentStatus = SegmentStatus.PENDING

    def effective_gap_ms(self, margin_ms: int = 400) -> int:
        """Usable gap duration after subtracting safety margins."""
        return max(0, self.gap_duration_ms - margin_ms)

    def is_usable(self) -> bool:
        """True when segment has fitted TTS audio ready for mixing."""
        return self.status == SegmentStatus.FITTED and self.tts_audio is not None

    def update_word_count(self) -> None:
        self.text_word_count = len(self.text.split()) if self.text.strip() else 0


@dataclass
class ADProject:
    video_url: str
    video_title: str = ""
    context: str = ""                          # User-provided context
    audio_path: str | None = None              # Path to extracted WAV audio
    segments: list[ADSegment] = field(default_factory=list)
    original_video_path: str | None = None     # Path to downloaded video file
    mixed_video_path: str | None = None        # Path to final video with AD
    step: int = 1                              # Current workflow step (1–4)

    @property
    def fitted_segments(self) -> list[ADSegment]:
        return [s for s in self.segments if s.is_usable()]

    @property
    def overflow_segments(self) -> list[ADSegment]:
        return [s for s in self.segments if s.status == SegmentStatus.OVERFLOW]

    @property
    def skipped_segments(self) -> list[ADSegment]:
        return [s for s in self.segments if s.status == SegmentStatus.SKIPPED]
